### ISSUE TITLE
Serial port not working after browser refresh

### ISSUE THREAD

**Issue by tresf** [qzindustries/qz-print#37]
Browser refresh crashes communication with serial port.

```
Exception in thread "Thread-25" java.lang.UnsatisfiedLinkError: Native Library (.dll/.so/.jnilib) already loaded in another classloader
at java.lang.ClassLoader.loadLibrary1(Unknown Source)
    at java.lang.ClassLoader.loadLibrary0(Unknown Source)
    at java.lang.ClassLoader.loadLibrary(Unknown Source)
    at java.lang.Runtime.load0(Unknown Source)
    at java.lang.System.load(Unknown Source)
    at jssc.SerialNativeInterface.<clinit>(SerialNativeInterface.java:172)
    at jssc.SerialPortList.<clinit>(SerialPortList.java:43)
    at qz.SerialIO.fetchSerialPorts(SerialIO.java:194)
    at qz.PrintApplet.startJavaScriptListener(PrintApplet.java:215)
    at qz.PrintApplet.access$000(PrintApplet.java:64)
    at qz.PrintApplet$1.run(PrintApplet.java:148)
    at java.security.AccessController.doPrivileged(Native Method)
    at qz.PrintApplet.run(PrintApplet.java:143)
    at java.lang.Thread.run(Unknown Source)

```

After communication with the author of jSSC, we are recommending this work-around.  Will leave bug open since there is an Oracle recommended fix using the nativelib tag which does not require reloading the JVM each time, but would require changes to the jSSC codebase.

Interim solution:  Add the `separate_jvm` parameter to the applet with a value of `true' as pictured below.

 ![image](https://cloud.githubusercontent.com/assets/6345473/4396051/38261b1c-4431-11e4-949f-c5ce6cfef082.png)

**Comment by tresf** [comment]
Closing as the `separate_jvm` parameter has been acceptable for the client which reported this.  QZ Tray should not suffer this limitation..
